name: GitHub Action Demo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths-ignore: .github
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "15 06 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: branch + event
        run: |
          echo "${{ github.event_name }}"
          echo "${{ github.event.type }}"
          echo "${{ github.ref_name }}"
      - uses: actions/checkout@v3.0.2
      - name: list repos
        run: ls -alH
