name: GitHub Action Demo

# Controls when the workflow will run
on:
# Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
#    paths-ignore: .github
#  pull_request:
#    branches: [ "main" ]
#  schedule:
#    - cron: "15 06 * * 0"
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: contexts runner
        run: echo "${{ toJSON(runner) }}"
      - name: contexts github
        run: echo "${{ toJSON(github) }}"
      - name: contexts env
        run: echo "${{ toJSON(env) }}"
      - name: contexts matrix
        run: echo "${{ toJSON(matrix) }}"

      - name: branch + event
        run: |
          echo "${{ github.event_name }}"
          echo "${{ github.ref_name }}"
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: list repos
        run: ls -alH
